DROP DATABASE IF EXISTS n7hgccvh2pv79jo2;

CREATE DATABASE n7hgccvh2pv79jo2;

USE n7hgccvh2pv79jo2;

CREATE TABLE burgers (
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  eaten BOOLEAN NOT NULL DEFAULT 0
);